### ISSUE TITLE
Affect of IoT Edge SDK, Python Libs and CLI extensions Updates and Depreciated APIs

### ISSUE THREAD

**Issue by mustafakasap** [Azure/live-video-analytics#101]
@naiteeks
 
There were recent updates on the IoT Edge Python SDK and CLI extensions. This affects the notebook samples and few affects are:
- Creating ACR is fine but the CLI command to get back ACR password is failing.
- CLI command to create IoTEdge Device is depreciated. IoTEdge Device conn string is not being returned in expected format (because of new version of IoTEdge Device API interfaces)
- Remote method invocation etc. methods not working unless you update the Python libs to new versions in proper way (meaning uninstall and reinstall, unfortunaltey update is not working... iot team working on it...)
-...

**Comment by gadamilan** [comment]
@naiteeks 
Can we close this now?

**Comment by naiteeks** [comment]
@gadamilan  - this has been resolved with [https://github.com/Azure/live-video-analytics/pull/109](https://github.com/Azure/live-video-analytics/pull/109). We can close this issue now.
