### ISSUE TITLE
Need install argument

### ISSUE THREAD

**Issue by monjha** [Azure/live-video-analytics#106]
https://github.com/Azure/live-video-analytics/blob/eeaefa4c82b4ca2d1a7802f5ad750ee2d5faa40b/utilities/video-analysis/deepstream/app/start.sh#L9

**Comment by gadamilan** [comment]
@nicolasbotto - Can you please take a look at this?

**Comment by gadamilan** [comment]
@nicolasbotto - Can we close this issue now?

**Comment by naiteeks** [comment]
@gadamilan - we can close this issue now.
