### ISSUE TITLE
Feature request - consider support for update RTSP URL for an existing downstream camera device 

### ISSUE THREAD

**Issue by guybartal** [Azure/live-video-analytics#117]
currently, RTSP URL is read-only, when a user wants to change the URL the only way to do it is to delete the camera and add it again with the new URL.

**Comment by gadamilan** [comment]
Which direct method are you referring to? You can deactivate (not delete) the graph and perform a set operation on it to update the RTSP URL

**Comment by guybartal** [comment]
I mean once the graph is set to a RTSP stream, the URL is read-only and cannot be changed, is there a reason?

![image](https://user-images.githubusercontent.com/3179107/95010206-1a0a1f80-0630-11eb-9405-c11174f4b61f.png)

**Comment by gadamilan** [comment]
@sseiber @KishorIoT 
This is related to IoT Central template. Can you please take a look at this request?

**Comment by sseiber** [comment]
@guybartal - this is just a decision we made for the reference sample. We didn't want to separate the "camera hardware device" from the "IoT Hub device". We thought of them as one entity.

**Comment by gadamilan** [comment]
@guybartal 
Given Scott's response, I am closing this issue.

cc @sseiber
