### ISSUE TITLE
How to record the specific instance to record the video?

### ISSUE THREAD

**Issue by waitingkuo** [Azure/live-video-analytics#122]
Hi,

I followed this tutorial https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/event-based-video-recording-tutorial to setup a event based topology but I created multiple instances.

To enable my business logic apps to notify the signal-gate to record the video I need to setup this route
    
    "ObjectCounterToLVA": "FROM /messages/modules/objectCounter/outputs/objectCountTrigger INTO BrokeredEndpoint(\"/modules/lvaEdge/inputs/recordingTrigger\")" 

There's no information about the stream id or GraphInstance ID, so every single instance's IoTHubNode will listen the same Endpoint. If I have multiple instances (same topology). How can I record the specific instance but not all.

**Comment by rodrigb** [comment]
Hi @waitingkuo,

You can use the same named queue to trigger different graphs by adding an **eventTarget** property to your events per example below:

```javascript
{
    "message": {
        "systemProperties": {
            // This id will be used as correlation id in the absence of an explicit one 
            "message-id": "d145092a-3288-4348-a9b9-a5ca1b55d514"
        },
        "appProperties": {
            "eventType": "Microsoft.Media.Graph.Signaling.SignalGateTrigger",
            "eventTarget": "/graphInstances/myGraphInstanceName",
            "correlationId": "863a321a-b3ae-4bf3-b596-a521457fa4fe",    // Optional correlation id
            "dataVersion": "1.0"
        },
        "body": {

        }
    }
}
``` 

-Rodrigo

**Comment by waitingkuo** [comment]
hi @rodrigb 
thank you it works.

**Comment by rodrigb** [comment]
Awesome, thanks for the update!
