### ISSUE TITLE
Does lvaextension with Grpc support Python 3.7?

### ISSUE THREAD

**Issue by waitingkuo** [Azure/live-video-analytics#123]
Codes from https://github.com/Azure/live-video-analytics/blob/master/utilities/video-analysis/notebooks/Yolo/yolov4/yolov4-grpc-icpu-onnx/lvaextension/server/inference_engine.py#L124 use the [toreadyonly()](https://docs.python.org/3/library/stdtypes.html#memoryview.toreadonly) method of `memoryview` which is introduced in Python3.8. 

I wonder is there any alternative way to do so that I can use Python 3.7 since [Microsoft's ONNXRuntime Base Images](https://hub.docker.com/_/microsoft-azureml-onnxruntimefamily) are using Python 3.7.

**Comment by mustafakasap** [comment]
Memview comes with Python 3.7.9:  https://docs.python.org/3.7/library/functions.html#func-memoryview
You just need to update docker file to switch to Python3.7.9

Another solution is to use LVA-gRPC without shared memory option. There is another option where you can transfer data between LVA and LVAExtension over grpc again but embedding data into the message (so not shared over memory)

please see details of [MediaStreamDescriptor  ](https://github.com/Azure/live-video-analytics/tree/master/contracts/grpc)Protofile for exploring this non-sharedmem data transfer option.

One last option is to use custom dockerfile where onnxruntime can be installed on even Python 3.6.

from https://github.com/Azure/live-video-analytics/tree/master/contracts/grpc

```proto
// 
// Media Stream Descriptor 
//
// Describes the media type that will flow in a single direction of the stream.
//
message MediaStreamDescriptor {
  
  oneof stream_identifier {
    GraphIdentifier graph_identifier = 1;     // Media Stream graph identifier
    string extension_identifier = 2;          // Media Stream extension identifier
  }

  MediaDescriptor media_descriptor = 5;       // Session media information.

  // Additional data transfer properties. If none is set, it is assumed
  // that all content will be transferred through messages (embedded transfer).
  oneof data_transfer_properties {
    SharedMemoryBufferTransferProperties shared_memory_buffer_transfer_properties = 10;
  }
}
```

**Comment by mustafakasap** [comment]
@waitingkuo  one another option is to use your own ONNX custom image. Here is an example how one of the LVA extension sample uses onnxruntime:

https://github.com/Azure/live-video-analytics/blob/master/utilities/video-analysis/notebooks/Yolo/yolov3/yolov3-grpc-icpu-onnx/lvaextension/Dockerfile

as you can see here it is using Python3.8 for "toreadonly"
https://github.com/Azure/live-video-analytics/blob/cf82d5da03777408d489976334147139d3d02a67/utilities/video-analysis/notebooks/Yolo/yolov3/yolov3-grpc-icpu-onnx/lvaextension/Dockerfile#L1

and here it is installing onnx runtime on this very slim container image:
https://github.com/Azure/live-video-analytics/blob/cf82d5da03777408d489976334147139d3d02a67/utilities/video-analysis/notebooks/Yolo/yolov3/yolov3-grpc-icpu-onnx/lvaextension/Dockerfile#L10

you may prefer such container file also

**Comment by gadamilan** [comment]
@waitingkuo 
Does this answer your question?

**Comment by gadamilan** [comment]
@waitingkuo 
Closing this due to lack of response. Please reopen if this is still an issue.
