### ISSUE TITLE
Failure deploying graph using example

### ISSUE THREAD

**Issue by chilljl** [Azure/live-video-analytics#125]
Trying to run step 12 of  "deploy_to_iot_edge_device.ipmyb"  (Deploy LVA & Rocket to an IoT Edge Device). Every step has worked up until:

sys.path.append('../../../utilities/video-analysis/shared/graph_manager')
from graph_manager import GraphManager

moduleId = "lvaEdge" # Must be same as the name that we assigned to LVA module in the "deployment.lvaedge_rocketserver_rtspsim.template.json" file
operationsApiVersion = "1.0"  # Must be same as the version number in the "topology.json" file

graphManager = GraphManager(iotHubConnString, iotDeviceId, moduleId, operationsApiVersion)

--------------------------------------------------------------

ValueError                                Traceback (most recent call last)
<ipython-input-12-e29288284907> in <module>
      5 operationsApiVersion = "1.0"  # Must be same as the version number in the "topology.json" file
      6 
----> 7 graphManager = GraphManager(iotHubConnString, iotDeviceId, moduleId, operationsApiVersion)

~/live-video-analytics/utilities/video-analysis/shared/graph_manager/graph_manager.py in __init__(self, ioThubConnectionString, deviceId, moduleId, operationsApiVersion)
     30         self._apiVersion = operationsApiVersion
     31 
---> 32         self._registryManager = IoTHubRegistryManager(self._iotHubConnStr)
     33 
     34     def InvokeModuleMethod(self, methodName, payload):

~/live-video-analytics/utilities/video-analysis/notebooks/common/lva_conda_env/lib/python3.6/site-packages/azure/iot/hub/iothub_registry_manager.py in __init__(self, connection_string)
     63         :rtype: :class:`azure.iot.hub.IoTHubRegistryManager`
     64         """
---> 65         self.auth = ConnectionStringAuthentication(connection_string)
     66         self.protocol = protocol_client(self.auth, "https://" + self.auth["HostName"])
     67         self.amqp_svc_client = iothub_amqp_client(

~/live-video-analytics/utilities/video-analysis/notebooks/common/lva_conda_env/lib/python3.6/site-packages/azure/iot/hub/auth.py in __init__(self, connection_string)
     24     def __init__(self, connection_string):
     25         super(ConnectionStringAuthentication, self).__init__(
---> 26             connection_string
     27         )  # ConnectionString __init__
     28 

~/live-video-analytics/utilities/video-analysis/notebooks/common/lva_conda_env/lib/python3.6/site-packages/azure/iot/hub/connection_string.py in __init__(self, connection_string)
     72         :raises: ValueError if provided connection_string is invalid
     73         """
---> 74         self._dict = _parse_connection_string(connection_string)
     75         self._strrep = connection_string
     76 

~/live-video-analytics/utilities/video-analysis/notebooks/common/lva_conda_env/lib/python3.6/site-packages/azure/iot/hub/connection_string.py in _parse_connection_string(connection_string)
     34     """
     35     cs_args = connection_string.split(CS_DELIMITER)
---> 36     d = dict(arg.split(CS_VAL_SEPARATOR, 1) for arg in cs_args)
     37     if len(cs_args) != len(d):
     38         # various errors related to incorrect parsing - duplicate args, bad syntax, etc.

ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by chilljl** [comment]
Ok, I see one problem. In create_azure_services.ipymb, the iotHubConnString variable is created using  iotHubConnString = !az iot hub show-connection-string --hub-name $iotHubServiceName --output tsv

This command is depreciated, so it inputs the depreciation message **"This command has been deprecated and will be removed in a future release. Use 'IoT Extension (azure-iot) connection-string command (az iot hub connection-string show)' instead.**"  instead of the connection string into the variable.

**Comment by naiteeks** [comment]
@ycshu086   - can you look into this issue?

**Comment by naiteeks** [comment]
Thank you @chilljl for reporting this issue. We have updated that command line, removed the deprecated command and updated it with the new command. Can you try again and let us know if you are able to get past this issue?

**Comment by gadamilan** [comment]
@chilljl 
I am closing this as the issue has been fixed. Please reopen if you still see issues.
