### ISSUE TITLE
AAD Permission Requirements

### ISSUE THREAD

**Issue by RKrokson** [Azure/live-video-analytics#160]
I don't see AAD permission requirements listed here in GitHub or in any of the LVA on IoT Edge docs that point to this script. However, running the script in internal MS subscriptions fails when attempting to create the role definition for the service principal. Once this fails the rest of the script hangs is unable to finish. I'm assuming this is due to missing AAD permissions on our tenant. 

I've tested in a MSDN/Visual Studio subscription, where I control AAD, and the script works as expected. 

Could the pre-reqs sections be updated to include the AAD permissions required for creating the custom role definition?

**Comment by anilmur** [comment]
Ack, following up.

**Comment by naiteeks** [comment]
Hello @RKrokson - thank you for the feedback. Docs have now been updated with a note in the pre-requisites section.

**Comment by RKrokson** [comment]
Thanks for making the change. Closing the issue.
