### ISSUE TITLE
Motion-Detection API mismatch

### ISSUE THREAD

**Issue by RKrokson** [Azure/live-video-analytics#161]
The 'Quickstart: Detect motion and emit events', link below, has us set the topologyUrl in step 5 under 'Run the sample program'.  The url is pointing to version 2.0. This fails when running the rest of the step with a 'version 2.0 is not supported' error. Switching the url to point to version 1.0 allows me to complete the rest of the steps.

I checked the setup scripts at the beginning and it looks like the resources are set to use version 1.0.  Maybe the docs were updated before all of the code was updated to version 2.0

https://docs.microsoft.com/azure/media-services/live-video-analytics-edge/detect-motion-emit-events-quickstart?pivots=programming-language-csharp&source=docs#run-the-sample-program

**Comment by anilmur** [comment]
Checking...

**Comment by naiteeks** [comment]
hi @RKrokson  - can you confirm that in the deployment manifest you are using has the lvaEdge module use the mcr image: mcr.microsoft.com/media/live-video-analytics:2

![image](https://user-images.githubusercontent.com/42254991/105211526-378cc780-5b01-11eb-81b3-38b800d93da1.png)

**Comment by RKrokson** [comment]
Yes, I used the LVA resource setup script which has that module in place.

**Comment by naiteeks** [comment]
it looks like there is a manifest file which was previously deployed is still getting picked up. Can you do the following:
1. Restart the iotedge device using the following command in your VM: **sudo systemctl iotedge restart**
2. Re-deploy the manifest file. Make sure the right one is deployed. If your manifest template is named deployment.template.json, it will create a manifest by the name: **deployment.json**. Deploy this manifest.
3. Wait for a few seconds and try again.

If things are still not working, please let us know.

**Comment by RKrokson** [comment]
In early January I was able to reproduce the issue across multiple deployments. I would start from scratch after deleting the resources and setup scripts. I've since deleted all of the resources because this was a quickstart/lab. 

Do you want me to re-create from scratch to see if I can reproduce the issue?

**Comment by naiteeks** [comment]
yes please. I just ran the template on my machine and was able to run thru without errors.

**Comment by RKrokson** [comment]
This works now. I found the cloned repo on my machine from late Dec/early Jan and it was indeed calling the version 1.0 image. Thanks for verifying.

**Comment by naiteeks** [comment]
Awesome. Closing the issue now.

**Comment by gadamilan** [comment]
Closing as this has been resolved
