### ISSUE TITLE
Custom Model for Light and Heavy DNN

### ISSUE THREAD

**Issue by Petrichor2020** [Azure/live-video-analytics#177]
Hi, I was looking to use a custom model for the light and heavy DNN for the cascaded pipeline. However, I am not able to figure out how I can do the same. Please can you help regarding this?

**Comment by fvneerden** [comment]
Hi Petrichor2020,

Thanks for your interest in LVA. I'm not sure I understand your question and where you're blocked. Can you elaborate on it? Happy to help you forward.

**Comment by Petrichor2020** [comment]
Hi,
  I was able to run the reference app successfully. From what I was able to understand for Pipeline 1, the light neural network is a tiny Yolo model and the heavy deep neural network is the yolov3 model both trained on the coco dataset. My team was looking to use this pipeline with a custom model (maybe like RCNN) trained on our domain-specific dataset for detecting labels specific to our problem. We were looking to use this LVA framework in conjunction with a drone feed for solving a  set of domain-specific problems.

Thank you for your help!

**Comment by fvneerden** [comment]
Hi,
That would be possible. You can bring your own model to LVA. You can do this by integrating with the lvaExtention module. We have both HTTP and gRPC support. 
https://docs.microsoft.comazure/media-services/live-video-analytics-edge/use-your-model-quickstart?pivots=programming-language-csharp
https://docs.microsoft.com/azure/media-services/live-video-analytics-edge/analyze-live-video-use-your-grpc-model-quickstart?pivots=programming-language-csharp

**Comment by Petrichor2020** [comment]
Hi,
  Thanks for your answer. That is one possibility we are looking to explore. However, my doubt was in regard to the rocket app. Is it possible to replace the internal models (light and heavy DNN) in the rocket pipeline?

**Comment by naiteeks** [comment]
Hi @Petrichor2020  - you definitely can do that :). The [Dockerfile for Rocket](https://github.com/Azure/live-video-analytics/blob/master/ref-apps/rocket/csharp/Dockerfile) should be updated to then call the models you want to use. 

In the docker file shared above, we are calling Yolov3 and tinyYolov3 in line numbers 66 and 67. You can change the entries there to point to the models that you want to use.

**Comment by gadamilan** [comment]
@Petrichor2020  - I am closing this based on previous comment from @naiteeks 
Please reopen if there are follow-up questions
