### ISSUE TITLE
Signal Gate not blocking media

### ISSUE THREAD

**Issue by dennisfelczy** [Azure/live-video-analytics#218]
I am trying to use a Signal Gate in LVA to only inference when an IoT Hub Message is received. But somehow I cannot get it to work. As soon as I activate the Instance LVA directly starts inferencing. Do you maybe have an idea what could be the problem ?

Attached you find the 
[Instance.txt](https://github.com/Azure/live-video-analytics/files/6545508/Instance.txt)
[Topology.txt](https://github.com/Azure/live-video-analytics/files/6545509/Topology.txt)

Topology and Instance json I created:

**Comment by fvneerden** [comment]
Hi, The signalgate will not hold off when the downstream node is a http extension or grpc extension. So you would need to place a motion detection in front of the http extension/grpc extension and use that.

**Comment by dennisfelczy** [comment]
Thanks for the reply.  So controling inferencing with IoT Messages is currently not possible ?

**Comment by fvneerden** [comment]
You can, but you will have to include that logic in your own AI module and route IoT messages to your module.

**Comment by dennisfelczy** [comment]
Thanks for the clarification
