### ISSUE TITLE
minor update on yolo_v3.app

### ISSUE THREAD

**Issue by mustafakasap** [Azure/live-video-analytics#4]
Renaming variable names and a short comment on normalized coordinates (by spec def)
   

 # coordinates are normalized (optional comment)
        width = (x2 - x1) / iw
        height = (y2 - y1) / ih
        left = x1 / iw
        top = y1 / ih
        
        dobj = {
            "type" : "entity",
            "entity" : {
                "tag" : {
                    "value" : tags[idx_[1].tolist()],
                    "confidence" : scores[tuple(idx_)].tolist()
                },
                "box" : {
                    "l" : left,
                    "t" : top,
                    "w" : width,
                    "h" : height
                }
            }
        }
   OR
        # coordinates are normalized(optional comment)       
        dobj = {
            "type" : "entity",
            "entity" : {
                "tag" : {
                    "value" : tags[idx_[1].tolist()],
                    "confidence" : scores[tuple(idx_)].tolist()
                },
                "box" : {
                    "l" : x1 / iw,
                    "t" : y1 / ih,
                    "w" : (x2 - x1) / iw,
                    "h" : (y2 - y1) / ih
                }
            }
        }

**Comment by gadamilan** [comment]
In PR
