### ISSUE TITLE
Support for ARM processors?

### ISSUE THREAD

**Issue by NeverOddOrEven** [Azure/live-video-analytics#58]
I have a Jetson Nano with Azure IoT. I would love to try LVA but there are no docker images for ARM64 architectures. Any plans to release an ARM64 build?

**Comment by gadamilan** [comment]
ARM64 is on the roadmap but we don't have a schedule to share currently.

**Comment by NeverOddOrEven** [comment]
Cool. Thanks for the update. I'll keep playing with the DeepStream SDK for now!
