### ISSUE TITLE
Stuck at RecordingStarted

### ISSUE THREAD

**Issue by amarrmb** [Azure/live-video-analytics#59]
Hi,

To explain a bit about my setup & issue:
1) I tried with the sample application for continuous video recording tutorial and it worked flawlessly with the RTSPSimulator (https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/continuous-video-recording-tutorial) This was done on a VM as provided in the sample example.
2) Next, i assigned the module to my existing IoT Edge device. This is also running fine as per the logs (note this is on a different IoT Hub)
3) This existing IoT edge device has a different RTSP application, which provides the output on a different URL. Note that this URL doesnt have username or password.
4) I then used the c2d-console-app to use DirectMethod for my lvaEdge. I modified the operations.json & appsettings.json to ensure it reflects the correct ip address & IoT hub connection string respectively.
5) On using the DirectMethods as provided in c2d-console-app, i can see the messages are going towards lvaEdge module and i can see the RecordingStarted event.  However i dont see RecordingEnd/Stopped which i am expected to see as compared to the VM setup.

So the question is:
1) How do i start with debugging here?
If i do iotedge log lvaEdge, i get the following log
[lva_edge.txt](https://github.com/Azure/live-video-analytics/files/4817428/lva_edge.txt)

On the IoTHubMonitor, i see following message:
`[IoTHubMonitor] [10:45:45 PM] Message received from [DGX_device/lvaEdge]:
{
  "body": {
    "outputType": "assetName",
    "outputLocation": "sampleAsset-CVRToAMSAsset-sample-graph-1"
  },
  "applicationProperties": {
    "topic": "/subscriptions/22b4e5a3-9229-45e2-a9f6-8bbc0a6ebdd3/resourceGroups/AMS-Demo/providers/microsoft.media/mediaservices/amsmediaservice",
    "subject": "/graphInstances/sample-graph-1/sinks/assetSink",
    "eventType": "Microsoft.Media.Graph.Operational.RecordingStarted",
    "eventTime": "2020-06-23T05:45:45.672Z",
    "dataVersion": "1.0"
  }
}`

I waited around 30 mins to see if the status changes, but it doesn't. Note i was able to delete the topology afterward, so the module seems to be active.

2) How do you debug if the rtsp connection was successful? I tried checking with VLC and it worked for me on the same network. However i did not see any logs to understand if there could be any issue on the connection front.

**Comment by anilmur** [comment]
Hi @amarrmb, thanks for contacting us. At a high level, I suspect that you have hit a known issue where the "RecordingStarted" event is emitted even though the module has not been able to connect to the RSTP source. Please try the following:

1. In the deployment manifest, update the logging settings:
        "logLevel": "Verbose",
        "logCategories": "Application,Events, MediaPipeline",
2. Re-deploy the manifest, and re-run the graph, and then share the LVA Edge logs

Thanks

**Comment by anilmur** [comment]
Hi @amarrmb  - have you been able to resolve your issue? We'll close this out this week. Please feel free to contact us directly via amshelp@microsoft.com if you have further questions. Thanks

**Comment by amarrmb** [comment]
Hi @anilmur ,

I tried to redo the steps today and i am seeing following error:
```


<6> 2020-07-17 06:12:00.577 +00:00 Application: Module telemetry is enabled. System usage data that helps Microsoft improve this product will be reported.
<6> 2020-07-17 06:12:02.147 +00:00 Events: {
  "id": "<removed>",
  "topic": "/subscriptions/<removed>/resourceGroups/AMS-Demo/providers/microsoft.media/mediaservices/amsmediaservice",
  "subject": "",
  "eventType": "Microsoft.Media.Graph.Diagnostics.RuntimeError",
  "eventTime": "2020-07-17T06:12:02.099Z",
  "data": {
    "code": "MediaAccountAccessError",
    "details": [
      {
        "code": "MethodNotAllowed",
        "target": "https://management.azure.com/"
      }
    ]
  },
  "dataVersion": "1.0"
```

For the messages received over IoT Hub, i see following error message:
```
[IoTHubMonitor] [11:12:06 PM] Message received from [DGX_device/lvaEdge]:
{
  "body": {
    "code": "MediaAccountAccessError",
    "details": [
      {
        "code": "0",
        "target": "/subscriptions/<removed>/resourceGroups/AMS-Demo/providers/microsoft.media/mediaservices/amsmediaservice"
      }
    ]
  },
  "applicationProperties": {
    "topic": "/subscriptions/<removed>/resourceGroups/AMS-Demo/providers/microsoft.media/mediaservices/amsmediaservice",
    "subject": "",
    "eventType": "Microsoft.Media.Graph.Diagnostics.RuntimeError",
    "eventTime": "2020-07-17T06:00:38.664Z",
    "dataVersion": "1.0"
  }
}

```

As a pre-requisite, i ensured that i completed following steps:
1) https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/create-custom-azure-resource-manager-role-how-to
Followed by 
2) https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/deploy-iot-edge-device

I ensured that the AadSecret(aadServicePrincipalPassword), aadTenantId & aadClientId(aadserviceprincipapappid) are properly updated in the module twin.

**Comment by anilmur** [comment]
That error suggests that your media service account is not in one of the supported regions: 

canadaeast, centralus, eastus2, francecentral, japanwest, northcentralus, switzerlandnorth, uksouth, westcentralus, westus2, eastus2euap, centraluseuap.

Can you please check?

**Comment by amarrmb** [comment]
Hi,

Yes my resource is in eastus and i don't see that supported in the list you provided. Let me recreate a new instance in the above region and try it out.

**Comment by amarrmb** [comment]
Hi Anil,

I created a new MediaService resource in eastus2, redid the AD & service principle step with this resource and redeployed on my device with the updated module twin. I am still seeing issue (slightly different error)

On the device, i see following logs:
```
$ iotedge logs -f lvaEdge
<6> 2020-07-17 18:16:37.985 +00:00 Application: Module telemetry is enabled. System usage data that helps Microsoft improve this product will be reported.

<6> 2020-07-17 18:16:40.174 +00:00 Application: The module is now running.
<6> 2020-07-17 18:17:40.119 +00:00 Application: Request started: Method name: 'GraphInstanceList'.
<6> 2020-07-17 18:17:40.317 +00:00 Application: Request completed: Status=OK Elapsed=152ms.
<6> 2020-07-17 18:18:01.115 +00:00 Application: Request started: Method name: 'GraphTopologySet'.
<6> 2020-07-17 18:18:01.391 +00:00 Application: Request completed: Status=Created Elapsed=273ms.
<6> 2020-07-17 18:18:17.546 +00:00 Application: Request started: Method name: 'GraphInstanceSet'.
<6> 2020-07-17 18:18:17.660 +00:00 Application: Request completed: Status=Created Elapsed=113ms.
<6> 2020-07-17 18:20:05.291 +00:00 Application: Request started: Method name: 'GraphInstanceActivate'.
<6> 2020-07-17 18:20:06.205 +00:00 Events: {
  "id": "<removed>",
  "topic": "/subscriptions/<removed>/resourceGroups/AMS-Demo/providers/microsoft.media/mediaservices/amsmediaservice",
  "subject": "/graphInstances/sample-graph-1/sinks/assetSink",
  "eventType": "Microsoft.Media.Graph.Operational.RecordingStarted",
  "eventTime": "2020-07-17T18:20:06.090Z",
  "correlationId": "<removed>",
  "data": {
    "outputType": "assetName",
    "outputLocation": "sampleAsset-CVRToAMSAsset-sample-graph-1"
  },
  "dataVersion": "1.0"
}
<6> 2020-07-17 18:20:06.340 +00:00 Application: Request completed: Status=OK Elapsed=1048ms.
<6> 2020-07-17 18:20:06.983 +00:00 Events: {
  "id": "<removed>",
  "topic": "/subscriptions/<removed>/resourceGroups/AMS-Demo/providers/microsoft.media/mediaservices/amsmediaservice",
  "subject": "",
  "eventType": "Microsoft.Media.Graph.Diagnostics.RuntimeError",
  "eventTime": "2020-07-17T18:20:06.967Z",
  "data": {
    "code": "MediaAccountAccessError",
    "details": [
      {
        "code": "NotFound",
        "target": "https://management.azure.com/"
      }
    ]
  },
  "dataVersion": "1.0"
}

```

On the event endpoint, following is the error seen:

```
[IoTHubMonitor] [11:30:05 AM] Message received from [DGX_device/lvaEdge]:
{
  "body": {
    "code": "MediaAccountAccessError",
    "details": [
      {
        "code": "NotFound",
        "target": "https://management.azure.com/"
      }
    ]
  },
  "applicationProperties": {
    "topic": "/subscriptions/<removed>/resourceGroups/AMS-Demo/providers/microsoft.media/mediaservices/amsmediaservice",
    "subject": "",
    "eventType": "Microsoft.Media.Graph.Diagnostics.RuntimeError",
    "eventTime": "2020-07-17T18:30:05.772Z",
    "dataVersion": "1.0"
  }
}

```

**Comment by anilmur** [comment]
Checking...

**Comment by anilmur** [comment]
The hypothesis is that there were some leftover files cached in the VM when you changed AMS accounts. Please try the following:

1. Go to the Azure Portal, locate your IoT Hub, and click the IoT Edge device (lva-sample-device). Then click on "Set Modules" at the top, and in the page that opens up, delete the "lvaEdge" module
2. Go to the VM, and just in case, run "sudo systemctl restart iotedge"
3. Go to the directory that you used in the deployment manifest's Binds section. If you used the steps [here](https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/deploy-iot-edge-device#granting-permissions-to-device-storage), then the directory should be /var/lib/azuremediaservices
4. Delete all files and subfolders in this directory
5. Re-deploy the deployment manifest

You should now be good to go...

**Comment by amarrmb** [comment]
Thanks Anil, it helped!
I am able to get data on AMS on my setup. There is a potential issue mostly at my end where my docker container is probably not correctly streaming the data, but the main issue here seems to be resolved.
I will play around it further and report any additional issues (if i encounter them). You can close this issue, thanks.

**Comment by gadamilan** [comment]
Closing as this is resolved
