### ISSUE TITLE
Unable to get video stream from yolov3-onnx

### ISSUE THREAD

**Issue by akashperfect** [Azure/live-video-analytics#78]
As mentioned in the documentation trying for https://github.com/Azure/live-video-analytics/tree/master/utilities/video-analysis/yolov3-onnx#view-video-stream-with-inferencing-overlays

Sending video frames aka images in jpeg format to url http://127.0.0.1:8080/score?stream=test-stream
But unable to get any output on http://127.0.0.1:8080/stream/test-stream

Code tried
```
headers = {
  'Content-Type': 'image/jpeg'
}
url = "http://127.0.0.1:8080/score?stream=test-stream"

while True:
   # code to update traffic.jpeg image
   with open('traffic.jpeg', 'rb') as f:
            response = requests.request("POST", url, headers=headers, data = f.read(), stream=True)
            print(response.text.encode('utf8'))
```
Response that gets printed as part of above code
```
b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n'
```

Although same code is working to get an image output using the annotate endpoint.
Can you give a code example on how it works.

**Comment by gadamilan** [comment]
Hi,
Just to confirm, did you build the container yourself using the dockerfile or are you using the prebuild one from MCR?

**Comment by akashperfect** [comment]
Yes I built the container myself by cloning this repo and running these commands
```
docker build . -t yolov3-onnx:latest
docker run  --name my_yolo_container -p 8080:80 -d  -i yolov3-onnx:latest
```

**Comment by akashperfect** [comment]
Removing the '-' worked in this url http://127.0.0.1:8080/score?stream=test-stream

**Comment by gadamilan** [comment]
Thanks for letting us know
