### ISSUE TITLE
Broken Link in "IoT Central gateway module LVA edge"

### ISSUE THREAD

**Issue by naveen-repo-src** [Azure/live-video-analytics#84]
Broken Link in "IoT Central gateway module LVA edge" ref apps , please update link in README.md
Link :https://docs.microsoft.com/en-gb/azure/iot-central/retail/tutorial-video-analytics-build-module 
https://docs.microsoft.com/en-gb/azure/iot-central/retail/tutorial-video-analytics-create-app-

**Comment by avkewalr-msft** [comment]
Thanks Naveen, I will look into this

**Comment by avkewalr-msft** [comment]
@naveen-repo-src - we have fixed the broken link issues, thanks for flagging, let us know if anything else

**Comment by naveen-repo-src** [comment]
still couldn't find Video Analytics - Object and motion detection under retail category in Azure Iot Central. Can you please check 
![Screenshot from 2020-08-12 20-48-03](https://user-images.githubusercontent.com/61347637/90033504-2b444900-dcdd-11ea-9459-20632012613c.png)

**Comment by KishorIoT** [comment]
These links are fixed. could you try again.  Video analytics - object and motion detection is deployed to https://apps.azureiotcentral.com/build

**Comment by naveen-repo-src** [comment]
Thanks its working now
